# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import clients_pb2 as clients__pb2
GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clients_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateClient = channel.unary_unary(
                '/clients.ClientService/CreateClient',
                request_serializer=clients__pb2.CreateClientRequest.SerializeToString,
                response_deserializer=clients__pb2.ClientResponse.FromString,
                _registered_method=True)
        self.GetAllClients = channel.unary_unary(
                '/clients.ClientService/GetAllClients',
                request_serializer=clients__pb2.GetAllClientsRequest.SerializeToString,
                response_deserializer=clients__pb2.ClientListResponse.FromString,
                _registered_method=True)
        self.GetClientById = channel.unary_unary(
                '/clients.ClientService/GetClientById',
                request_serializer=clients__pb2.GetClientByIdRequest.SerializeToString,
                response_deserializer=clients__pb2.ClientResponse.FromString,
                _registered_method=True)
        self.UpdateClient = channel.unary_unary(
                '/clients.ClientService/UpdateClient',
                request_serializer=clients__pb2.UpdateClientRequest.SerializeToString,
                response_deserializer=clients__pb2.ClientResponse.FromString,
                _registered_method=True)
        self.UpdatePassword = channel.unary_unary(
                '/clients.ClientService/UpdatePassword',
                request_serializer=clients__pb2.UpdatePasswordRequest.SerializeToString,
                response_deserializer=clients__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.DeleteClient = channel.unary_unary(
                '/clients.ClientService/DeleteClient',
                request_serializer=clients__pb2.DeleteClientRequest.SerializeToString,
                response_deserializer=clients__pb2.MessageResponse.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClient,
                    request_deserializer=clients__pb2.CreateClientRequest.FromString,
                    response_serializer=clients__pb2.ClientResponse.SerializeToString,
            ),
            'GetAllClients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllClients,
                    request_deserializer=clients__pb2.GetAllClientsRequest.FromString,
                    response_serializer=clients__pb2.ClientListResponse.SerializeToString,
            ),
            'GetClientById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientById,
                    request_deserializer=clients__pb2.GetClientByIdRequest.FromString,
                    response_serializer=clients__pb2.ClientResponse.SerializeToString,
            ),
            'UpdateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClient,
                    request_deserializer=clients__pb2.UpdateClientRequest.FromString,
                    response_serializer=clients__pb2.ClientResponse.SerializeToString,
            ),
            'UpdatePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePassword,
                    request_deserializer=clients__pb2.UpdatePasswordRequest.FromString,
                    response_serializer=clients__pb2.MessageResponse.SerializeToString,
            ),
            'DeleteClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteClient,
                    request_deserializer=clients__pb2.DeleteClientRequest.FromString,
                    response_serializer=clients__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clients.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clients.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/CreateClient',
            clients__pb2.CreateClientRequest.SerializeToString,
            clients__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/GetAllClients',
            clients__pb2.GetAllClientsRequest.SerializeToString,
            clients__pb2.ClientListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/GetClientById',
            clients__pb2.GetClientByIdRequest.SerializeToString,
            clients__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/UpdateClient',
            clients__pb2.UpdateClientRequest.SerializeToString,
            clients__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/UpdatePassword',
            clients__pb2.UpdatePasswordRequest.SerializeToString,
            clients__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/DeleteClient',
            clients__pb2.DeleteClientRequest.SerializeToString,
            clients__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
