# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"\x17\n\x15GetAllProductsRequest\"#\n\x15GetProductByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"W\n\x14\x43reateProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08imageUrl\x18\x04 \x01(\t\"c\n\x14UpdateProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08imageUrl\x18\x05 \x01(\t\"\"\n\x14\x44\x65leteProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"W\n\x0fProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\"\n\x07product\x18\x03 \x01(\x0b\x32\x11.products.Product\"k\n\x13ProductListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12#\n\x08products\x18\x04 \x03(\x0b\x32\x11.products.Product\"9\n\x15\x44\x65leteProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x94\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08imageUrl\x18\x05 \x01(\t\x12\x15\n\rimagePublicId\x18\x06 \x01(\t\x12\x10\n\x08isActive\x18\x07 \x01(\x08\x12\x13\n\x0b\x64\x61teCreated\x18\x08 \x01(\t2\x9a\x03\n\x0eProductService\x12P\n\x0eGetAllProducts\x12\x1f.products.GetAllProductsRequest\x1a\x1d.products.ProductListResponse\x12L\n\x0eGetProductById\x12\x1f.products.GetProductByIdRequest\x1a\x19.products.ProductResponse\x12J\n\rCreateProduct\x12\x1e.products.CreateProductRequest\x1a\x19.products.ProductResponse\x12J\n\rUpdateProduct\x12\x1e.products.UpdateProductRequest\x1a\x19.products.ProductResponse\x12P\n\rDeleteProduct\x12\x1e.products.DeleteProductRequest\x1a\x1f.products.DeleteProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALLPRODUCTSREQUEST']._serialized_start=28
  _globals['_GETALLPRODUCTSREQUEST']._serialized_end=51
  _globals['_GETPRODUCTBYIDREQUEST']._serialized_start=53
  _globals['_GETPRODUCTBYIDREQUEST']._serialized_end=88
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=90
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=177
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=179
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=278
  _globals['_DELETEPRODUCTREQUEST']._serialized_start=280
  _globals['_DELETEPRODUCTREQUEST']._serialized_end=314
  _globals['_PRODUCTRESPONSE']._serialized_start=316
  _globals['_PRODUCTRESPONSE']._serialized_end=403
  _globals['_PRODUCTLISTRESPONSE']._serialized_start=405
  _globals['_PRODUCTLISTRESPONSE']._serialized_end=512
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=514
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=571
  _globals['_PRODUCT']._serialized_start=574
  _globals['_PRODUCT']._serialized_end=722
  _globals['_PRODUCTSERVICE']._serialized_start=725
  _globals['_PRODUCTSERVICE']._serialized_end=1135
# @@protoc_insertion_point(module_scope)
